//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public Auction()
        {
            this.Notifications = new HashSet<Notification>();
            this.Orders = new HashSet<Order>();
            this.R_Auction_CurrentUsers = new HashSet<R_Auction_CurrentUsers>();
            this.Reports = new HashSet<Report>();
        }
    
        public int id { get; set; }
        public int idCard { get; set; }
        public int idUserSeller { get; set; }
        public System.DateTime beginDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string status { get; set; }
        public string type { get; set; }
        public Nullable<decimal> currentAmount { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> idCurrentUser { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<R_Auction_CurrentUsers> R_Auction_CurrentUsers { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
    }
}
