//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.Auctions = new HashSet<Auction>();
            this.R_Card_Color = new HashSet<R_Card_Color>();
            this.R_Card_Mechanic = new HashSet<R_Card_Mechanic>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public decimal cost { get; set; }
        public decimal minValue { get; set; }
        public string status { get; set; }
        public int manaCost { get; set; }
        public Nullable<int> power { get; set; }
        public Nullable<int> toughness { get; set; }
        public bool isFoil { get; set; }
        public int idRarity { get; set; }
        public int idCategory { get; set; }
        public Nullable<int> idSupertype { get; set; }
    
        public virtual ICollection<Auction> Auctions { get; set; }
        public virtual Category Category { get; set; }
        public virtual Rarity Rarity { get; set; }
        public virtual Supertype Supertype { get; set; }
        public virtual ICollection<R_Card_Color> R_Card_Color { get; set; }
        public virtual ICollection<R_Card_Mechanic> R_Card_Mechanic { get; set; }
    }
}
