//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color
    {
        public Color()
        {
            this.R_Card_Color = new HashSet<R_Card_Color>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<R_Card_Color> R_Card_Color { get; set; }
    }
}
