//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Auction_CurrentUsers
    {
        public int id { get; set; }
        public int idCurrentUser { get; set; }
        public decimal amount { get; set; }
        public Nullable<int> idAuction { get; set; }
    
        public virtual Auction Auction { get; set; }
        public virtual User User { get; set; }
    }
}
