//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rarity
    {
        public Rarity()
        {
            this.Cards = new HashSet<Card>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Card> Cards { get; set; }
    }
}
