//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int id { get; set; }
        public string description { get; set; }
        public string route { get; set; }
        public int idReportType { get; set; }
        public int idAuction { get; set; }
    
        public virtual Auction Auction { get; set; }
        public virtual ReportType ReportType { get; set; }
    }
}
