//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardTrade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Auctions = new HashSet<Auction>();
            this.Auctions1 = new HashSet<Auction>();
            this.Profiles = new HashSet<Profile>();
            this.R_Auction_CurrentUsers = new HashSet<R_Auction_CurrentUsers>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
    
        public virtual ICollection<Auction> Auctions { get; set; }
        public virtual ICollection<Auction> Auctions1 { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<R_Auction_CurrentUsers> R_Auction_CurrentUsers { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
